require('main.plugins.deps')
require('main.plugins.editor')
require('main.plugins.ai')
require('main.plugins.treesitter')
require('main.plugins.lsp')
require('main.plugins.linter')
require('main.plugins.git')
require('main.plugins.testing')
